server:
  port: 8091

project:
  service:
    code: TEST
    name: TEST project


# JWT Option
jwt:
  auth:
    name: X-AUTH-TOKEN
  access:
    name: X-ACCESS-TOKEN
  refresh:
    name: X-REFRESH-TOKEN


