server:
  port: 8091

project:
  service:
    code: TEST
    name: TEST project

# Swagger
swagger:
  path: /api/gradle-utils/v${swagger.api.version}/**
  api:
    title: Gradle-template
    desc: Gradle Template Description
    version: 1.0
  contact:
    name: Jeongho Yun
    url: Swagger.co.kr
    email: wjdgh7587@gmail.com
  license:
    name: Jeongho Yun
    url: wjdgh7587@gmail.com
  external:
    desc: Spring Gradle Multi Module Utils
    path: /index.html

# springdoc
springdoc:
  version: 1.0.0
  api-docs:
#    enabled: true
    path: /api/swagger/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-operation-id: true
    operations-sorter: alpha
    tags-sorter: alpha
    supported-submit-methods: application/json


# JWT Option
jwt:
  auth:
    name: X-AUTH-TOKEN
  access:
    name: X-ACCESS-TOKEN
  refresh:
    name: X-REFRESH-TOKEN


