apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: test-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:lates
        command: ["mysql"]
        args:
        - "-u"
        - root
        - "-p"
        - "--ssl-mode=DISABLED"  # SSL 비활성화t
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: test-dev
spec:
  selector:
    app: mysql
  #type: NodePort
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      #nodePort: 32006



