# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
  namespace: test-dev
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ./mnt/data

---

# pvc1.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-1
  namespace: test-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

# pvc2.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-2
  namespace: test-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

---

# pvc3.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-3
  namespace: test-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi



