server:
  port: 8091


springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /api-ui.html
    disable-swagger-default-url: true
    display-operation-id: true
    operations-sorter: alpha
    tags-sorter: alpha
