apiVersion: v1
kind: Pod
metadata:
    name: mypod
spec:
    containers:
        - name: firstcontater
          image: nginx:stable
          envFrom:
              - configMapRef:
                    name: my-config
