version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    #image: 'gitlab/glab:v1.36.0-arm64'
    mem_limit: 512m
    #mem_reservation: 128m
    #cpus: 1	
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://host.docker.internal:8087'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['initial_root_password'] = 'test!@'
    ports:
      - '8087:8087'
      # - '443:443'
      - '2222:22'
    # volumes:
    #   - './mnt/gitlab/config:/etc/gitlab'
    #   - './mnt/gitlab/logs:/var/log/gitlab'
    #   - './mnt/gitlab/data:/var/opt/gitlab'
    #shm_size: '256m'
#     networks:
#       - service
# networks:
#   service:
#     driver: bridge
